" -------------------
" vim-plug and packages
" -------------------

" make sure vim-plug is installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
  \| endif

call plug#begin('~/.vim/plugged')

" motions
Plug 'easymotion/vim-easymotion'

" flex syntax 
Plug 'justinmk/vim-syntax-extra'

" delete surrounding characters
Plug 'tpope/vim-surround'

" match beginning and end of more tags with %
Plug 'andymass/vim-matchup'

" commenting plugin
Plug 'scrooloose/nerdcommenter'
nnoremap <C-/> :call nerdcommenter#Comment(0,"toggle")<CR>
vnoremap <C-/> :call nerdcommenter#Comment(0,"toggle")<CR>
nnoremap <C-_> :call nerdcommenter#Comment(0,"toggle")<CR>
vnoremap <C-_> :call nerdcommenter#Comment(0,"toggle")<CR>
nnoremap // :call nerdcommenter#Comment(0,"toggle")<CR>
vnoremap // :call nerdcommenter#Comment(0,"toggle")<CR>

let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'

" be able to have multiple cursors like sublime text
Plug 'terryma/vim-multiple-cursors'
" map multiple line selection to be the same as in sublime text
let g:multi_cursor_start_word_key = '<C-d>'
let g:multi_cursor_next_key = '<C-d>'
let g:multi_cursor_quit_key = '<Esc>'

" install fuzzy finder for vim
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
" make fzf bound to ctrl-p
nnoremap <C-p> :<C-u>FZF<CR>
" make file search bound to ctrl-f
nnoremap <C-f> :Rg<CR>

" autocomplete brackets
Plug 'jiangmiao/auto-pairs'

" good light colorscheme
Plug 'endel/vim-github-colorscheme'

call plug#end()

" ----------------
" GENERAL SETTINGS
" ----------------

" for nerdcommenter
filetype plugin on

" tab settings
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
" color settings
syntax on
set background=dark
colorscheme slate

" highlight search
set hlsearch
set number 
" set number relativenumber
set norelativenumber
set cursorline

" press j and k simultaneously for escape so you don't have to move hands
imap jk <Esc>
imap kj <Esc>

set dictionary="/usr/dict/words"

" remove highlighted search words 
nnoremap \ :noh<CR>

" make a hotkey for searching
nnoremap <C-g> :s///g 

" ignore case while searching
set ignorecase


" make copy paste to/from system work
set clipboard=unnamedplus

" remove status bar at bottom
set laststatus=0

" make undo history permanent
set undofile
set undodir=~/.vim/undodir

nnoremap <SPACE> <Nop>
let mapleader=" "
